//! Attribute macros for the kwabi ABI.
//!
//! `#[guarded_body]` makes "must not panic" true by construction. See
//! `kwabi::guarded` for the full rationale.
//!
//! `require_unwind!` is the crate-level check for extensions that hand-write
//! their trampolines instead of using the macro.

use proc_macro::TokenStream;
use quote::{format_ident, quote};
use syn::{parse_macro_input, ItemFn, ReturnType, Type};

/// The build-time panic-strategy check, as one place so the message cannot
/// drift between the attribute macro and the crate-level macro.
fn panic_strategy_check() -> proc_macro2::TokenStream {
    quote! {
        // A build-time check that the panic strategy can actually be contained.
        //
        // `#[guarded_body]` works by catching a panic inside this crate's own
        // std. With panic="abort" there is no unwinding to catch, so the first
        // panic aborts the whole postmaster -- and nothing about the code looks
        // wrong. `cfg(panic = ...)` is evaluated in THIS crate, so the error
        // points at the developer's own code rather than at the SDK, which is
        // what makes it actionable.
        #[cfg(panic = "abort")]
        compile_error!(
            "kwabi: this crate must be built with panic=\"unwind\", but is \
    being built with panic=\"abort\". A panic in a guarded body cannot be caught \
    under that profile, so it would abort the PostgreSQL postmaster instead of \
    returning KWABI_ERR_PANICKED. Remove `panic = \"abort\"` from your profile, \
    or set `panic = \"unwind\"` explicitly."
        );
    }
}

/// Generate a panic-safe `KwabiBodyFn` trampoline for a function.
///
/// The annotated function keeps its ordinary Rust signature and body. This
/// macro emits a second, `#[no_mangle] extern "C"` function named
/// `<name>__kwabi_body` whose signature is exactly what `kwabi_try` expects,
/// and whose body catches panics **inside this crate's own std**.
///
/// Catching inside the same std is the entire trick: a panic from a separately
/// built extension is a foreign exception to the runtime's std, so the runtime
/// cannot catch it — but the extension's own std can catch its own panic.
///
/// # Requirements
///
/// - The function must take exactly one argument, `&mut T`.
/// - It must return `()` or `Result<(), E>` with `E: Debug`.
/// - The crate must be built with `panic = "unwind"` (the default). This is
///   checked at compile time and fails the build with an actionable message.
#[proc_macro_attribute]
pub fn guarded_body(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let func = parse_macro_input!(item as ItemFn);
    let name = &func.sig.ident;
    let trampoline = format_ident!("{}__kwabi_body", name);

    // Extract the single `&mut T` argument's pointee type.
    let arg_ty: Type = match func.sig.inputs.len() {
        1 => match &func.sig.inputs[0] {
            syn::FnArg::Typed(pat) => match &*pat.ty {
                Type::Reference(r) => (*r.elem).clone(),
                other => {
                    return syn::Error::new_spanned(
                        other,
                        "#[guarded_body] requires the argument to be `&mut T`",
                    )
                    .to_compile_error()
                    .into();
                }
            },
            other => {
                return syn::Error::new_spanned(other, "#[guarded_body] requires a typed argument")
                    .to_compile_error()
                    .into();
            }
        },
        _ => {
            return syn::Error::new_spanned(
                &func.sig,
                "#[guarded_body] requires exactly one argument: `&mut T`",
            )
            .to_compile_error()
            .into();
        }
    };

    // Return type must be () or Result<(), E>; both map through IntoStatus, so
    // the only thing worth rejecting is a type that is neither.
    if let ReturnType::Type(_, t) = &func.sig.output {
        let ok = match &**t {
            Type::Tuple(tup) => tup.elems.is_empty(),
            Type::Path(_) => true, // assumed Result; the trait bound enforces it
            _ => false,
        };
        if !ok {
            return syn::Error::new_spanned(
                t,
                "#[guarded_body] requires the return type to be `()` or `Result<(), E>`",
            )
            .to_compile_error()
            .into();
        }
    }

    let check = panic_strategy_check();

    let expanded = quote! {
        #func

        #check

        #[doc = concat!("Panic-safe trampoline for `", stringify!(#name), "`.")]
        #[doc = ""]
        #[doc = "Generated by `#[guarded_body]`. Pass this to `kwabi_try`: its"]
        #[doc = "signature is exactly `KwabiBodyFn`."]
        #[no_mangle]
        pub unsafe extern "C" fn #trampoline(
            arg: *mut ::std::os::raw::c_void,
            out: *mut ::kwabi::guarded::KwabiErrorAbi,
        ) -> i32 {
            let outcome = ::kwabi::guarded::run_guarded::<#arg_ty, _, _>(arg, #name);
            let status = ::kwabi::guarded::status_from_outcome(outcome);

            // If the body reported a structured error, copy it into the
            // caller's struct. The runtime cannot see an extension's errors --
            // they live in this crate -- so the trampoline carries them across
            // into the same `out` the caller handed to kwabi_try.
            ::kwabi::guarded::publish_report(out, status);

            status
        }
    };

    expanded.into()
}

/// Fail the build if this crate is compiled with `panic = "abort"`.
///
/// For extensions that hand-write their trampolines rather than using
/// `#[guarded_body]`. Invoke once at crate root:
///
/// ```ignore
/// kwabi::require_unwind!();
/// ```
///
/// It expands to nothing when the profile is correct, so it costs nothing at
/// runtime and nothing to read.
///
/// Note: with a proc-macro the *ideal* home for this check is the crate root,
/// because `#[cfg(panic = ...)]` at module scope would let it fire once for the
/// whole crate. Rust does not permit a proc-macro to expand to a module-scope
/// attribute, so this must be invoked as a macro. That is why it exists
/// separately rather than being automatic.
#[proc_macro]
pub fn require_unwind(_item: TokenStream) -> TokenStream {
    panic_strategy_check().into()
}
