#!/usr/bin/env python3
"""Generate src/raw.rs: one unsafe method per KwabiV1 slot, except transactions.

The argument and return types are copied from the KwabiV1 mirror in src/lib.rs,
so a generated method cannot disagree with the mirror it calls through. The
header is checked by the layout test in src/raw.rs, not here.

Usage: python3 tools/gen_raw.py > src/raw.rs
"""
import re
import sys

EXCLUDED_PREFIXES = ("transaction_",)  # the transactions API: not exposed yet


def struct_body(src):
    start = src.index("pub struct KwabiV1 {")
    open_brace = src.index("{", start)
    depth, i = 1, open_brace + 1
    while depth:
        if src[i] == "{":
            depth += 1
        elif src[i] == "}":
            depth -= 1
        i += 1
    return src[open_brace + 1:i - 1]


def top_level_split(text, sep):
    parts, cur, depth, j = [], "", 0, 0
    while j < len(text):
        if text.startswith("->", j):
            cur += "->"
            j += 2
            continue
        ch = text[j]
        if ch in "(<[{":
            depth += 1
        elif ch in ")>]}":
            depth -= 1
        if ch == sep and depth == 0:
            parts.append(cur.strip())
            cur = ""
        else:
            cur += ch
        j += 1
    if cur.strip():
        parts.append(cur.strip())
    return parts


def parse_slot(ty):
    """Option<[unsafe ]extern "C" fn(ARGS) [-> RET]> -> (args, ret)."""
    ty = " ".join(ty.split())
    ty = re.sub(r",\s*>$", ">", ty)  # rustfmt leaves a trailing comma before the close
    ty = re.sub(r"<\s+", "<", ty)     # ...and sometimes a space after an opening '<'
    m = re.fullmatch(r'Option<(?:unsafe )?extern "C" fn\((.*)\)(?: -> (.*))?>', ty)
    if not m:
        raise SystemExit(f"unrecognised slot type: {ty}")
    args = [a for a in top_level_split(m.group(1), ",") if a]
    ret = m.group(2).strip() if m.group(2) else "()"
    return args, ret


def main():
    src = open("src/lib.rs").read()
    fields = []
    for field in top_level_split(struct_body(src), ","):
        m = re.search(r"pub (\w+)\s*:\s*(.*)", field, re.S)
        if not m or m.group(1) == "version":
            continue
        fields.append((m.group(1), m.group(2)))

    slots = [(n, t) for n, t in fields if not n.startswith(EXCLUDED_PREFIXES)]
    out = []
    w = out.append
    w("// @generated by tools/gen_raw.py from the KwabiV1 mirror in src/lib.rs.")
    w("// Do not edit by hand; regenerate.")
    w("")
    w("//! The raw ABI: every slot in kwabi.h except the transactions API, one")
    w("//! method each. Each is unsafe: it calls a C function pointer through the")
    w("//! table, and is only sound while the runtime's signature matches the mirror.")
    w("//! A missing slot panics with its name, rather than calling NULL.")
    w("")
    w("use super::*;")
    w("use std::os::raw::c_char;")
    w("")
    w("/// Calls the ABI table directly.")
    w("pub struct Raw<'a> {")
    w("    api: &'a KwabiV1,")
    w("}")
    w("")
    w("impl<'a> Raw<'a> {")
    w("    pub(crate) fn new(api: &'a KwabiV1) -> Self {")
    w("        Raw { api }")
    w("    }")
    for name, ty in slots:
        args, ret = parse_slot(ty)
        if args and args[-1] == "...":
            # A C variadic slot (ereport, elog). The method takes the fixed
            # arguments and one message, passed through "%s": a format string
            # cannot cross the safe/raw boundary unchecked.
            # Both variadic slots are (code, fmt, ...): the fmt is replaced by "%s".
            fixed = args[:-2]
            params = ", ".join([f"a{i}: {t}" for i, t in enumerate(fixed)] + ["msg: *const c_char"])
            call_args = ", ".join([f"a{i}" for i in range(len(fixed))]
                                  + ['c"%s".as_ptr()', "msg"])
        else:
            params = ", ".join(f"a{i}: {t}" for i, t in enumerate(args))
            call_args = ", ".join(f"a{i}" for i in range(len(args)))
        sig_ret = "" if ret == "()" else f" -> {ret}"
        w("")
        w(f"    /// Slot `{name}`.")
        w("    ///")
        w("    /// # Safety")
        w("    ///")
        w("    /// The runtime must provide this slot with exactly this signature, and")
        w("    /// every pointer argument must be valid for the use the slot makes of it.")
        if len(args) + 1 > 7:  # clippy counts &self; its default limit is 7
            w("    #[allow(clippy::too_many_arguments)]")
        w(f"    pub unsafe fn {name}(&self{', ' if params else ''}{params}){sig_ret} {{")
        w(f'        (self.api.{name}.expect("{name}"))({call_args})')
        w("    }")
    w("}")
    w("")
    w("/// Every slot name `Raw` exposes, in header order. The test in lib.rs checks")
    w("/// this against kwabi.h.")
    w("pub const SLOTS: &[&str] = &[")
    for name, _ in slots:
        w(f'    "{name}",')
    w("];")
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
